# Generated by Django 2.2.4 on 2019-08-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('about', models.CharField(max_length=1024)),
                ('image_url', models.CharField(max_length=512)),
            ],
        ),
    ]
