# Generated by Django 2.2.4 on 2019-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigerweb', '0002_officer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='order',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
